//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5420
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.CompactFramework.Design.Data 2.0.50727.5420 版自动生成。
// 
namespace THOK.WES.DzInspurWarehouseOperationService {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WarehouseOperationServiceSoapBinding", Namespace="http://10.89.128.22:9080/L3/services/WarehouseOperationService")]
    public partial class WarehouseOperationServiceService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public WarehouseOperationServiceService() {
            this.Url = "http://10.89.128.22:9080/L3/services/WarehouseOperationService";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://chinasofti.webItfc.l3.lc.com", ResponseNamespace="http://10.89.128.22:9080/L3/services/WarehouseOperationService")]
        [return: System.Xml.Serialization.SoapElementAttribute("ScanNewBillReturn")]
        public string ScanNewBill() {
            object[] results = this.Invoke("ScanNewBill", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginScanNewBill(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ScanNewBill", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string EndScanNewBill(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://chinasofti.webItfc.l3.lc.com", ResponseNamespace="http://10.89.128.22:9080/L3/services/WarehouseOperationService")]
        [return: System.Xml.Serialization.SoapElementAttribute("HitShelfReturn")]
        public string HitShelf(string voucherNum) {
            object[] results = this.Invoke("HitShelf", new object[] {
                        voucherNum});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginHitShelf(string voucherNum, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("HitShelf", new object[] {
                        voucherNum}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndHitShelf(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://chinasofti.webItfc.l3.lc.com", ResponseNamespace="http://10.89.128.22:9080/L3/services/WarehouseOperationService")]
        [return: System.Xml.Serialization.SoapElementAttribute("HitShelfConfirmReturn")]
        public string HitShelfConfirm(string Param) {
            object[] results = this.Invoke("HitShelfConfirm", new object[] {
                        Param});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginHitShelfConfirm(string Param, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("HitShelfConfirm", new object[] {
                        Param}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndHitShelfConfirm(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://chinasofti.webItfc.l3.lc.com", ResponseNamespace="http://10.89.128.22:9080/L3/services/WarehouseOperationService")]
        [return: System.Xml.Serialization.SoapElementAttribute("HitShelfConfirmSJReturn")]
        public string HitShelfConfirmSJ(string Param) {
            object[] results = this.Invoke("HitShelfConfirmSJ", new object[] {
                        Param});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginHitShelfConfirmSJ(string Param, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("HitShelfConfirmSJ", new object[] {
                        Param}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndHitShelfConfirmSJ(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://chinasofti.webItfc.l3.lc.com", ResponseNamespace="http://10.89.128.22:9080/L3/services/WarehouseOperationService")]
        [return: System.Xml.Serialization.SoapElementAttribute("StockTakeReturn")]
        public string StockTake(string checkNum) {
            object[] results = this.Invoke("StockTake", new object[] {
                        checkNum});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginStockTake(string checkNum, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("StockTake", new object[] {
                        checkNum}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndStockTake(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://chinasofti.webItfc.l3.lc.com", ResponseNamespace="http://10.89.128.22:9080/L3/services/WarehouseOperationService")]
        [return: System.Xml.Serialization.SoapElementAttribute("StockTakeConfirmReturn")]
        public string StockTakeConfirm(string Param) {
            object[] results = this.Invoke("StockTakeConfirm", new object[] {
                        Param});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginStockTakeConfirm(string Param, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("StockTakeConfirm", new object[] {
                        Param}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndStockTakeConfirm(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://chinasofti.webItfc.l3.lc.com", ResponseNamespace="http://10.89.128.22:9080/L3/services/WarehouseOperationService")]
        [return: System.Xml.Serialization.SoapElementAttribute("StockMoveReturn")]
        public string StockMove(string storeMoveId) {
            object[] results = this.Invoke("StockMove", new object[] {
                        storeMoveId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginStockMove(string storeMoveId, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("StockMove", new object[] {
                        storeMoveId}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndStockMove(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://chinasofti.webItfc.l3.lc.com", ResponseNamespace="http://10.89.128.22:9080/L3/services/WarehouseOperationService")]
        [return: System.Xml.Serialization.SoapElementAttribute("StockMoveConfirmReturn")]
        public string StockMoveConfirm(string Param) {
            object[] results = this.Invoke("StockMoveConfirm", new object[] {
                        Param});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginStockMoveConfirm(string Param, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("StockMoveConfirm", new object[] {
                        Param}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndStockMoveConfirm(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://chinasofti.webItfc.l3.lc.com", ResponseNamespace="http://10.89.128.22:9080/L3/services/WarehouseOperationService")]
        [return: System.Xml.Serialization.SoapElementAttribute("StockOutReturn")]
        public string StockOut(string storeOutId) {
            object[] results = this.Invoke("StockOut", new object[] {
                        storeOutId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginStockOut(string storeOutId, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("StockOut", new object[] {
                        storeOutId}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndStockOut(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://chinasofti.webItfc.l3.lc.com", ResponseNamespace="http://10.89.128.22:9080/L3/services/WarehouseOperationService")]
        [return: System.Xml.Serialization.SoapElementAttribute("StockOutConfirmReturn")]
        public string StockOutConfirm(string Param) {
            object[] results = this.Invoke("StockOutConfirm", new object[] {
                        Param});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginStockOutConfirm(string Param, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("StockOutConfirm", new object[] {
                        Param}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndStockOutConfirm(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
    }
}
